// ConstantQuest — constant definitions
// All decimal digit strings were generated with mpmath at 130 digits of
// working precision and truncated to 100 digits after the decimal point,
// so they are not hand-typed / memorized values.

const CONSTANTS = [
  {
    id: 'pi',
    symbol: 'π',
    name: 'Pi',
    intPart: '3',
    digits: '1415926535897932384626433832795028841971693993751058209749445923078164062862089986280348253421170679',
    formula: 'Circumference ÷ Diameter of any circle',
    fact: 'Pi is irrational and transcendental. It shows up everywhere circles, waves, and periodic motion do — not just geometry.',
    color: '#ff6b6b'
  },
  {
    id: 'tau',
    symbol: 'τ',
    name: 'Tau',
    intPart: '6',
    digits: '2831853071795864769252867665590057683943387987502116419498891846156328125724179972560696506842341359',
    formula: 'τ = 2π, the ratio of a circle’s circumference to its radius',
    fact: 'Some mathematicians argue tau is the more "natural" circle constant since it directly relates radius to circumference, simplifying many formulas.',
    color: '#ffa94d'
  },
  {
    id: 'e',
    symbol: 'e',
    name: "Euler's Number",
    intPart: '2',
    digits: '7182818284590452353602874713526624977572470936999595749669676277240766303535475945713821785251664274',
    formula: 'lim(n→∞) (1 + 1/n)ⁿ',
    fact: 'The base of natural logarithms. It is the unique number whose exponential function equals its own derivative — the heartbeat of continuous growth.',
    color: '#51cf66'
  },
  {
    id: 'sqrt2',
    symbol: '√2',
    name: 'Pythagoras’ Constant',
    intPart: '1',
    digits: '4142135623730950488016887242096980785696718753769480731766797379907324784621070388503875343276415727',
    formula: 'The length of a right triangle’s hypotenuse when both legs = 1',
    fact: 'The first number ever proven irrational, by the ancient Greeks — reportedly a scandal for the Pythagoreans, who believed everything was ratios of whole numbers.',
    color: '#4dabf7'
  },
  {
    id: 'sqrt3',
    symbol: '√3',
    name: 'Theodorus’ Constant',
    intPart: '1',
    digits: '7320508075688772935274463415058723669428052538103806280558069794519330169088000370811461867572485756',
    formula: 'The length of the diagonal of a unit cube’s face-adjacent triangle; height of an equilateral triangle with side 2',
    fact: 'Named after Theodorus of Cyrene, who proved the irrationality of the square roots of non-square integers up to 17.',
    color: '#38d9a9'
  },
  {
    id: 'sqrt5',
    symbol: '√5',
    name: 'Square Root of 5',
    intPart: '2',
    digits: '2360679774997896964091736687312762354406183596115257242708972454105209256378048994144144083787822749',
    formula: '√5 appears directly in the formula for the golden ratio',
    fact: 'Central to the closed-form (Binet’s) formula for Fibonacci numbers, tying it directly to the golden ratio.',
    color: '#66d9e8'
  },
  {
    id: 'phi',
    symbol: 'φ',
    name: 'The Golden Ratio',
    intPart: '1',
    digits: '6180339887498948482045868343656381177203091798057628621354486227052604628189024497072072041893911374',
    formula: 'φ = (1 + √5) / 2',
    fact: 'The "most irrational" number — hardest to approximate with fractions. Appears in art, architecture, and the spirals of sunflowers and shells.',
    color: '#f7c948'
  },
  {
    id: 'silver',
    symbol: 'δS',
    name: 'The Silver Ratio',
    intPart: '2',
    digits: '4142135623730950488016887242096980785696718753769480731766797379907324784621070388503875343276415727',
    formula: 'δS = 1 + √2',
    fact: 'The golden ratio’s lesser-known cousin, generated by the "Pell numbers" the way phi is generated by Fibonacci numbers.',
    color: '#adb5bd'
  },
  {
    id: 'gamma',
    symbol: 'γ',
    name: 'Euler–Mascheroni Constant',
    intPart: '0',
    digits: '5772156649015328606065120900824024310421593359399235988057672348848677267776646709369470632917467495',
    formula: 'lim(n→∞) [ (1 + 1/2 + 1/3 + … + 1/n) − ln(n) ]',
    fact: 'Nobody knows if gamma is even irrational, let alone transcendental — one of the biggest open questions in number theory.',
    color: '#da77f2'
  },
  {
    id: 'ln2',
    symbol: 'ln 2',
    name: 'Natural Log of 2',
    intPart: '0',
    digits: '6931471805599453094172321214581765680755001343602552541206800094933936219696947156058633269964186875',
    formula: '∫₁² (1/x) dx',
    fact: 'Governs "doubling time" in exponential growth and decay — it’s the constant behind the rule-of-thumb "70 ÷ growth rate" for doubling.',
    color: '#69db7c'
  },
  {
    id: 'ln10',
    symbol: 'ln 10',
    name: 'Natural Log of 10',
    intPart: '2',
    digits: '3025850929940456840179914546843642076011014886287729760333279009675726096773524802359972050895982983',
    formula: '∫₁¹⁰ (1/x) dx',
    fact: 'The conversion factor between natural logarithms and base-10 (common) logarithms: log₁₀(x) = ln(x) / ln(10).',
    color: '#8ce99a'
  },
  {
    id: 'catalan',
    symbol: 'G',
    name: 'Catalan’s Constant',
    intPart: '0',
    digits: '9159655941772190150546035149323841107741493742816721342664981196217630197762547694793565129261151062',
    formula: 'Σ (−1)ⁿ / (2n+1)² for n = 0 to ∞',
    fact: 'Turns up in combinatorics and statistical mechanics (like counting domino tilings). Whether it’s irrational is still unproven.',
    color: '#e599f7'
  },
  {
    id: 'apery',
    symbol: 'ζ(3)',
    name: 'Apéry’s Constant',
    intPart: '1',
    digits: '2020569031595942853997381615114499907649862923404988817922715553418382057863130901864558736093352581',
    formula: 'Σ 1/n³ for n = 1 to ∞',
    fact: 'Roger Apéry stunned the math world in 1978 by proving this value is irrational — still the only odd zeta value proven irrational.',
    color: '#ff8787'
  },
  {
    id: 'plastic',
    symbol: 'ρ',
    name: 'The Plastic Number',
    intPart: '1',
    digits: '3247179572447460259609088544780973407344040569017333645340150503028278512455475940546993479817872803',
    formula: 'The real root of x³ = x + 1',
    fact: 'The 3D analogue of the golden ratio, discovered in 1928 by Dutch architect Dom Hans van der Laan for use in proportioning buildings.',
    color: '#ced4da'
  }
];

// Difficulty presets — number of digits (after the decimal point) tested
const DIFFICULTIES = [
  { id: 'easy',   label: 'Easy',   digits: 25 },
  { id: 'medium', label: 'Medium', digits: 50 },
  { id: 'hard',   label: 'Hard',   digits: 75 },
  { id: 'master', label: 'Master', digits: 100 }
];
